development:
  secret_key_base: 3b7cd727ee24e8444053437c36cc66c3

test:
  secret_key_base: db1298096034e50ed0fa1275d363e903a005fd1430ddc66e466a4b94316471a1bd0bd906ef4b71bf35dd7aae2055416570ea2bc211c364f4c63a991955621c5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

pi:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

